-- Speed Car Wash - Supabase database setup
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.wash_enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text not null,
  service text,
  message text,
  city text,
  state text,
  car_type text,
  preferred_date date,
  preferred_time text,
  address text,
  source text not null default 'website',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- If the table was created earlier with fewer columns, add the missing ones.
alter table public.wash_enquiries add column if not exists city text;
alter table public.wash_enquiries add column if not exists state text;
alter table public.wash_enquiries add column if not exists car_type text;
alter table public.wash_enquiries add column if not exists preferred_date date;
alter table public.wash_enquiries add column if not exists preferred_time text;
alter table public.wash_enquiries add column if not exists address text;
alter table public.wash_enquiries add column if not exists source text not null default 'website';
alter table public.wash_enquiries add column if not exists status text not null default 'pending';
alter table public.wash_enquiries add column if not exists created_at timestamptz not null default now();

alter table public.wash_enquiries enable row level security;

drop policy if exists "Allow public enquiry submission" on public.wash_enquiries;
create policy "Allow public enquiry submission"
on public.wash_enquiries
for insert
to anon
with check (true);
